spring:
  application:
    name: ChargingStatioOperationManagementServer
  datasource:
    url: jdbc:mysql://localhost:3306/charging_station_operation?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/,file:${file-upload.path}

# 文件上传配置
file-upload:
  path: ./uploads/
  url-prefix: /uploads/
springdoc:
  api-docs:
    enabled: true # 开启swagger文档
    path: /v3/api-docs # 配置swagger文档的数据访问路径
  swagger-ui:
    path: /swagger-ui.html # 访问swagger文档的路径
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规则
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql日志
  mapper-locations: classpath*:mapper/*.xml # 扫描mapper xml文件
  type-aliases-package: com.smileshark.entity # 别名包